Update secret upload command to use `secret bulk`
cloudflare/wrangler-action pull request #341
Opened 2024-12-29 16:24 UTC by shixzie

Replace the deprecated `secret:bulk` command with the updated `secret bulk` command for uploading secrets.

2025-01-22 17:54 UTC, jahands approved these changes

2025-02-10 14:49 UTC, Maximo-Guk commented
/approve

2025-02-10 14:59 UTC, Maximo-Guk commented
Hi @shixzie 👋! I think we'd want to add a version check for people on older versions of wrangler who don't yet have `wrangler secret bulk`, otherwise this would be a breaking change for people on these older versions.

2025-02-19 06:34 UTC, Maximo-Guk requested changes
See https://github.com/cloudflare/wrangler-action/pull/341#issuecomment-2648270092

2025-03-14 06:59 UTC, Phillip9587 commented
This is even more relevant now that wrangler v4 removed the deprecated `wrangler secret:bulk`.

2025-03-15 02:06 UTC, Maximo-Guk commented
Hey @Phillip9587 and @JustinINevill , we ended up releasing https://github.com/cloudflare/wrangler-action/releases/tag/v3.14.1 with these changes, let me know if that fixed things for y'all!

Thank you @shixzie for your contributions, will go ahead and close out this PR since it was superseded by https://github.com/cloudflare/wrangler-action/pull/358

2025-03-15 02:06 UTC, closed without merging

2025-03-15 15:34 UTC, JustinINevill commented
> Hey @Phillip9587 and @JustinINevill , we ended up releasing https://github.com/cloudflare/wrangler-action/releases/tag/v3.14.1 with these changes, let me know if that fixed things for y'all!
> 
> Thank you @shixzie for your contributions, will go ahead and close out this PR since it was superseded by #358

Works for me. Thanks very much!